lang = {
	user_student_projects : 'Student projects: ',
	user_mentor_projects : 'Mentor projects: ',
	user_no_projects : 'No projects',
	user_status_title : 'Status: ',
	user_final_reviews : 'Final reviews: ',
	user_grades_title : 'Grades:',
	user_marks_search : 'Search',
	user_select_criteria : 'Select criteria',
	user_select_categories: 'Select categories',
	user_final_review: 'Final Review',
	user_general_review: 'General',
	user_technical_review: 'Technical',
	user_no_technical_review: 'There is no technical review!',
	user_no_general_review: 'There is no general review!',
	user_next_step: 'Next step',
	user_loading: 'Loading',
	user_download: 'Download',
	user_select_projects: 'Select project or leave it empty to select all',
	user_no_meeting_info: 'No information about this meeting!',
	user_general_comment: 'General commentary:',
	user_criterion_name: 'Criterion name',
	user_mark: 'Mark',
	user_commentary: 'Commentary',
	user_date: 'Date'
};